[tool.poetry]
name = "cryptobot"
version = "0.1.0"
description = ""
authors = ["Raveme491 <michaelsdf491@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
